esphome:
  name: thermomodule-relay-x4
  friendly_name: thermomodule-relay-x4

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret 2_wifi_ssid
    password: !secret 2_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "fallback"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

output:
  - platform: gpio
    pin: GPIO23
    id: led
  - platform: gpio
    pin: GPIO32
    id: relay_pin_1
  - platform: gpio
    pin: GPIO33
    id: relay_pin_2
  - platform: gpio
    pin: GPIO25
    id: relay_pin_3
  - platform: gpio
    pin: GPIO26
    id: relay_pin_4

# Define the switches based on the relay pins
switch:
  - platform: output
    id: relay_1
    name: "Relay 1"
    output: relay_pin_1
  - platform: output
    id: relay_2
    name: "Relay 2"
    output: relay_pin_2
  - platform: output
    id: relay_3
    name: "Relay 3"
    output: relay_pin_3
  - platform: output
    id: relay_4
    name: "Relay 4"
    output: relay_pin_4

interval:
  - interval: 1000ms
    then:
      - output.turn_on: led
      - delay: 500ms
      - output.turn_off: led

i2c:
   - id: bus_a
     sda: GPIO21 #GPIO5
     scl: GPIO22 #GPIO4
     scan: True
     frequency: 400000

sensor:
  - platform: aht10
    variant: aht20
    id: my_aht10
    temperature:
      id: aht10_temp
      name: "Temperature"
    humidity:
      id: aht10_humi
      name: "Humidity"
    address: 0x38
    update_interval: 60s
  - platform: rotary_encoder  
    id: my_encoder
    pin_a:
      number: GPIO18
      mode: INPUT_PULLUP
    pin_b:
      number: GPIO19
      mode: INPUT_PULLUP

text_sensor:
  - platform: version
    name: "ESPHome Version"
    id: espversion
    hide_timestamp: true

climate:
  - platform: thermostat
    visual:
      min_temperature: 0 °C
      max_temperature: 80°C
      temperature_step: 0.5 °C
    name: "Thermo module 01"
    sensor: aht10_temp
    preset:
    -  name: Default
       default_target_temperature_low: 20.0
       default_target_temperature_high: 22.0
    min_cooling_off_time: 5s
    min_cooling_run_time: 5s
    min_heating_off_time: 5s
    min_heating_run_time: 5s
    min_idle_time: 5s
    cool_action:
      - switch.turn_on: relay_1
    heat_action:
      - switch.turn_on: relay_2
    idle_action:
      - switch.turn_off: relay_2
      - switch.turn_off: relay_1

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    reset_pin: GPIO16
    #lambda: |-
    #it.fill(COLOR_ON);
    #it.printf(64, 0, id(font4), TextAlign::TOP_CENTER, "Acquario %.1f° C", id(aht10_temp).state);
    lambda: |-
      it.printf(64, 0, id(font4), TextAlign::TOP_CENTER, "%s", id(espversion).state.c_str());
      it.strftime(0, 60, id(font2), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());
      it.printf(127, 23, id(font3), TextAlign::TOP_RIGHT , "%.1f°", id(aht10_temp).state);
      it.printf(127, 60, id(font3), TextAlign::BASELINE_RIGHT , "%.1f%%", id(aht10_humi).state);
time:
  - platform: homeassistant
    id: esptime
    
font:
  - file: '_fonts/slkscr.ttf'
    id: font1
    size: 8

  - file: '_fonts/BebasNeue-Regular.ttf'
    id: font2
    size: 48

  - file: '_fonts/arial.ttf'
    id: font3
    size: 14
    
  - file: '_fonts/Comfortaa-Regular.ttf'
    id: font4
    size: 14